#ifndef CONSTANTS_H
#define CONSTANTS_H

const int DEFAULT_SIZE_IN_CELLS = 4;
const int MAX_SIZE_IN_CELLS = 10;
const int MIN_SIZE_IN_CELLS = 2;
const int DEFAULT_WINDOW_HEIGHT = 400;
const int DEFAULT_WINDOW_WIDTH = 400;
const int DEFAULT_CELL_SIZE = DEFAULT_WINDOW_WIDTH / DEFAULT_SIZE_IN_CELLS;
const int ADDITIONAL_SIZE = 110;
const int BORDER_SIZE = 25;

#endif // CONSTANTS_H
